import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1778286992616 implements MigrationInterface {
    name = 'Migrations1778286992616'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "applications_status" ("id" SERIAL NOT NULL, "status" character varying NOT NULL DEFAULT 'DRAFT', "cnieStatus" character varying NOT NULL DEFAULT 'PENDING', "membersCnieStatus" character varying NOT NULL DEFAULT 'PENDING', "gradesStatus" character varying NOT NULL DEFAULT 'PENDING', "parentalAuthorizationStatus" character varying NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "applicationId" integer, CONSTRAINT "REL_de155f8fdccaf125d1e792fd27" UNIQUE ("applicationId"), CONSTRAINT "PK_5b1e0e1dd2282503e02bf678665" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applications" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL DEFAULT '', "lastName" character varying NOT NULL DEFAULT '', "dateOfBirth" TIMESTAMP, "identityCardNumber" character varying NOT NULL DEFAULT '', "city" character varying NOT NULL DEFAULT '', "region" character varying NOT NULL DEFAULT '', "phoneNumber" character varying NOT NULL DEFAULT '', "educationLevel" character varying NOT NULL DEFAULT '', "educationField" character varying NOT NULL DEFAULT '', "highschool" character varying NOT NULL DEFAULT '', "averageGrade" character varying NOT NULL DEFAULT '', "mathAverageGrade" character varying NOT NULL DEFAULT '', "ranking" character varying NOT NULL DEFAULT '', "mathRanking" character varying NOT NULL DEFAULT '', "numberOfStudentsInClass" character varying NOT NULL DEFAULT '', "hasPreviousExperiences" character varying NOT NULL DEFAULT '', "previousExperiences" text, "hasPreviousMTYMParticipations" character varying NOT NULL DEFAULT '', "previousMTYMParticipations" text, "motivations" text, "comments" text, "fileRegulationsUrl" character varying, "fileGradesUrl" character varying, "fileCnieUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "userId" integer, "statusId" integer, CONSTRAINT "REL_90ad8bec24861de0180f638b9c" UNIQUE ("userId"), CONSTRAINT "REL_2ccfa45ebf6c44b5f26a1a87ff" UNIQUE ("statusId"), CONSTRAINT "PK_938c0a27255637bde919591888f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "participant-details" ("id" SERIAL NOT NULL, "status" character varying NOT NULL DEFAULT 'DRAFTED', "gender" character varying NOT NULL DEFAULT '', "guardianFullName" character varying NOT NULL DEFAULT '', "guardianPhoneNumber" character varying NOT NULL DEFAULT '', "foodAllergy" character varying NOT NULL DEFAULT '[]', "nonFoodAllergy" character varying NOT NULL DEFAULT '[]', "allergyPrecaution" text, "illnessOrDisability" character varying NOT NULL DEFAULT '[]', "isOnMedication" character varying NOT NULL DEFAULT '', "medication" text, "needAssistance" character varying NOT NULL DEFAULT '', "specialAccommodations" text, "hasBeenHospitalized" character varying NOT NULL DEFAULT '', "hospitalizationReasons" text, "haveRoommatePreference" character varying NOT NULL DEFAULT '', "firstRoommateId" character varying NOT NULL DEFAULT '', "secondRoommateId" character varying NOT NULL DEFAULT '', "needDepartureShuttle" character varying NOT NULL DEFAULT '', "departureCity" character varying NOT NULL DEFAULT '', "needArrivalShuttle" character varying NOT NULL DEFAULT '', "arrivalCity" character varying NOT NULL DEFAULT '', "cityOfResidence" character varying NOT NULL DEFAULT '', "haveTalent" character varying NOT NULL DEFAULT '', "talentDescription" text, "workshops" character varying NOT NULL DEFAULT '[]', "filePhotoUrl" character varying, "fileParentalAuthorizationUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "userId" integer, CONSTRAINT "REL_79fdf313dbf97865fc0ac90b46" UNIQUE ("userId"), CONSTRAINT "PK_d8c7b91386d16ddec332fc9a5ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teams" ("id" SERIAL NOT NULL, "name" character varying NOT NULL DEFAULT '', "slogan" character varying NOT NULL DEFAULT '', "quadrigram" character varying NOT NULL DEFAULT '', "mentorFullname" character varying NOT NULL DEFAULT '', "leaderId" integer, CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "identifier" character varying NOT NULL DEFAULT '', "firstName" character varying NOT NULL DEFAULT '', "lastName" character varying NOT NULL DEFAULT '', "email" character varying NOT NULL DEFAULT '', "password" character varying NOT NULL DEFAULT '', "verified" boolean NOT NULL DEFAULT false, "qualified" boolean NOT NULL DEFAULT false, "verificationCode" character varying NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "applicationId" integer, "participantDetailsId" integer, "teamId" integer, CONSTRAINT "REL_315a6ad486c15783fb06517691" UNIQUE ("applicationId"), CONSTRAINT "REL_9738a2741dc47adb59bd369ea1" UNIQUE ("participantDetailsId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teams-access-code" ("id" SERIAL NOT NULL, "accessCode" character varying NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "teamId" integer, CONSTRAINT "PK_50b836675e49a364b0f1ba0f63d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plugins" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "isEnabled" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_bb3d17826b76295957a253ba73e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admin_users" ("id" SERIAL NOT NULL, "username" character varying NOT NULL DEFAULT '', "password" character varying NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_06744d221bb6145dc61e5dc441d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "applications_status" ADD CONSTRAINT "FK_de155f8fdccaf125d1e792fd277" FOREIGN KEY ("applicationId") REFERENCES "applications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_90ad8bec24861de0180f638b9cc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_2ccfa45ebf6c44b5f26a1a87ffe" FOREIGN KEY ("statusId") REFERENCES "applications_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant-details" ADD CONSTRAINT "FK_79fdf313dbf97865fc0ac90b46a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_6d5c85d3f2602450d1e615afae9" FOREIGN KEY ("leaderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_315a6ad486c15783fb065176918" FOREIGN KEY ("applicationId") REFERENCES "applications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_9738a2741dc47adb59bd369ea19" FOREIGN KEY ("participantDetailsId") REFERENCES "participant-details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_d1803064187c8f38e57a9c4984c" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams-access-code" ADD CONSTRAINT "FK_3d60c40a9dd17f35ba31cf30fa9" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "teams-access-code" DROP CONSTRAINT "FK_3d60c40a9dd17f35ba31cf30fa9"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_d1803064187c8f38e57a9c4984c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_9738a2741dc47adb59bd369ea19"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_315a6ad486c15783fb065176918"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_6d5c85d3f2602450d1e615afae9"`);
        await queryRunner.query(`ALTER TABLE "participant-details" DROP CONSTRAINT "FK_79fdf313dbf97865fc0ac90b46a"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_2ccfa45ebf6c44b5f26a1a87ffe"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_90ad8bec24861de0180f638b9cc"`);
        await queryRunner.query(`ALTER TABLE "applications_status" DROP CONSTRAINT "FK_de155f8fdccaf125d1e792fd277"`);
        await queryRunner.query(`DROP TABLE "admin_users"`);
        await queryRunner.query(`DROP TABLE "plugins"`);
        await queryRunner.query(`DROP TABLE "teams-access-code"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP TABLE "participant-details"`);
        await queryRunner.query(`DROP TABLE "applications"`);
        await queryRunner.query(`DROP TABLE "applications_status"`);
    }

}
