import { toLabelMap } from "./option.utils";

export const cityOptions = [
  { label: "Agadir", value: "agadir" },
  { label: "Agourai", value: "agourai" },
  { label: "Ahfir", value: "ahfir" },
  { label: "Ain Attig", value: "ainattig" },
  { label: "Ain El Aouda", value: "ainelaouda" },
  { label: "Ain Harrouda", value: "ainharrouda" },
  { label: "Ain Taoujdate", value: "aintaoujdate" },
  { label: "Ait Amira", value: "aitamira" },
  { label: "Ait Melloul", value: "aitmelloul" },
  { label: "Ait Ourir", value: "aitourir" },
  { label: "Al Aaroui", value: "alaaroui" },
  { label: "Al Hoceima", value: "alhoceima" },
  { label: "Aoulouz", value: "aoulouz" },
  { label: "Aourir", value: "aourir" },
  { label: "Aousserd", value: "aousserd" },
  { label: "Arfoud", value: "arfoud" },
  { label: "Assilah", value: "assilah" },
  { label: "Azemmour", value: "azemmour" },
  { label: "Azilal", value: "azilal" },
  { label: "Azrou", value: "azrou" },
  { label: "Bejaad", value: "bejaad" },
  { label: "Ben Ahmed", value: "benahmed" },
  { label: "Ben Guerir", value: "benguerir" },
  { label: "Beni Bouayach", value: "benibouayach" },
  { label: "Beni Ensar", value: "beniensar" },
  { label: "Beni Mellal", value: "benimellal" },
  { label: "Benslimane", value: "benslimane" },
  { label: "Berkane", value: "berkane" },
  { label: "Berrechid", value: "berrechid" },
  { label: "Biougra", value: "biougra" },
  { label: "Bir Anzarane", value: "biranzarane" },
  { label: "Bir Gandus", value: "birgandus" },
  { label: "Bir Lehlou", value: "birlehlou" },
  { label: "Bni Yakhlef", value: "bniyakhlef" },
  { label: "Bouarfa", value: "bouarfa" },
  { label: "Bouizakarne", value: "bouizakarne" },
  { label: "Boujdour", value: "boujdour" },
  { label: "Boumia", value: "boumia" },
  { label: "Bouznika", value: "bouznika" },
  { label: "Bouskoura", value: "bouskoura" },
  { label: "Casablanca", value: "casablanca" },
  { label: "Chefchaouen", value: "chefchaouen" },
  { label: "Chichaoua", value: "chichaoua" },
  { label: "Dakhla", value: "dakhla" },
  { label: "Dar Bouazza", value: "darbouazza" },
  { label: "Dcheira El Jihadia", value: "dcheiraeljihadia" },
  { label: "Demnate", value: "demnate" },
  { label: "Deroua", value: "deroua" },
  { label: "Drargua", value: "drargua" },
  { label: "Echemmaia", value: "echemmaia" },
  { label: "El Aioun Sidi Mellouk", value: "elaiounsidimellouk" },
  { label: "El Borouj", value: "elborouj" },
  { label: "El Gara", value: "elgara" },
  { label: "El Hajeb", value: "elhajeb" },
  { label: "El Jadida", value: "eljadida" },
  { label: "El Kelaa des Sraghna", value: "elkelaadessraghna" },
  { label: "El Ksiba", value: "elksiba" },
  { label: "El Marsa", value: "elmarsa" },
  { label: "Er-Rich", value: "errich" },
  { label: "Errachidia", value: "errachidia" },
  { label: "Essaouira", value: "essaouira" },
  { label: "Fez", value: "fez" },
  { label: "Fkih Ben Salah", value: "fkihbensalah" },
  { label: "Fnideq", value: "fnideq" },
  { label: "Guercif", value: "guercif" },
  { label: "Guelmim", value: "guelmim" },
  { label: "Guelta Zemmour", value: "gueltazemmour" },
  { label: "Gueznaia", value: "gueznaia" },
  { label: "Had Soualem", value: "hadsoualem" },
  { label: "Harhoura", value: "harhoura" },
  { label: "Hawza", value: "hawza" },
  { label: "Ifrane", value: "ifrane" },
  { label: "Imintanoute", value: "imintanoute" },
  { label: "Imouzzer Kandar", value: "imouzzerkandar" },
  { label: "Imzouren", value: "imzouren" },
  { label: "Inezgane", value: "inezgane" },
  { label: "Jerada", value: "jerada" },
  { label: "Jorf El Melha", value: "jorfelmelha" },
  { label: "Karia Ba Mohamed", value: "kariabamohamed" },
  { label: "Kasba Tadla", value: "kasbatadla" },
  { label: "Kenitra", value: "kenitra" },
  { label: "Khemisset", value: "khemisset" },
  { label: "Khenifra", value: "khenifra" },
  { label: "Khouribga", value: "khouribga" },
  { label: "Ksar El Kebir", value: "ksarelkebir" },
  { label: "Laattaouia", value: "laattaouia" },
  { label: "Laayoune", value: "laayoune" },
  { label: "Lahraouyine", value: "lahraouyine" },
  { label: "Lalla Mimouna", value: "lallamimouna" },
  { label: "Larache", value: "larache" },
  { label: "Lbir Jdid", value: "lbirjdid" },
  { label: "Lqliaa", value: "lqliaa" },
  { label: "Mahbes", value: "mahbes" },
  { label: "Marrakesh", value: "marrakesh" },
  { label: "Martil", value: "martil" },
  { label: "Mdiq", value: "mdiq" },
  { label: "Mechra Bel Ksiri", value: "mechrabelksiri" },
  { label: "Mediouna", value: "mediouna" },
  { label: "Mehdia", value: "mehdia" },
  { label: "Meknes", value: "meknes" },
  { label: "Mers El Kheir", value: "merselkheir" },
  { label: "Midelt", value: "midelt" },
  { label: "Missour", value: "missour" },
  { label: "Mohammedia", value: "mohammedia" },
  { label: "Moulay Abdellah", value: "moulayabdellah" },
  { label: "Moulay Ali Cherif", value: "moulayalicherif" },
  { label: "Mrirt", value: "mrirt" },
  { label: "Nador", value: "nador" },
  { label: "Nouaceur", value: "nouaceur" },
  { label: "Ouarzazate", value: "ouarzazate" },
  { label: "Oued Zem", value: "ouedzem" },
  { label: "Ouezzane", value: "ouezzane" },
  { label: "Oujda", value: "oujda" },
  { label: "Oulad Ayad", value: "ouladayad" },
  { label: "Oulad Berhil", value: "ouladberhil" },
  { label: "Oulad Tayeb", value: "ouladtayeb" },
  { label: "Oulad Teima", value: "ouladteima" },
  { label: "Ouislane", value: "ouislane" },
  { label: "Outat El Haj", value: "outatelhaj" },
  { label: "Rabat", value: "rabat" },
  { label: "Ras El Mae", value: "raselmae" },
  { label: "Ribate El Kheir", value: "ribateelkheir" },
  { label: "Sabaa Aiyoun", value: "sabaaaiyoun" },
  { label: "Safi", value: "safi" },
  { label: "Sale", value: "sale" },
  { label: "Sebt Gzoula", value: "sebtgzoula" },
  { label: "Sefrou", value: "sefrou" },
  { label: "Selouane", value: "selouane" },
  { label: "Settat", value: "settat" },
  { label: "Sidi Allal El Bahraoui", value: "sidiallelbahraoui" },
  { label: "Sidi Bennour", value: "sidibennour" },
  { label: "Sidi Bouknadel", value: "sidibouknadel" },
  { label: "Sidi Ifni", value: "sidiifni" },
  { label: "Sidi Kacem", value: "sidikacem" },
  { label: "Sidi Rahal Chatai", value: "sidirahalchatai" },
  { label: "Sidi Slimane", value: "sidislimane" },
  { label: "Sidi Slimane Echcharaa", value: "sidislimaneechcharaa" },
  { label: "Sidi Taibi", value: "siditaibi" },
  { label: "Sidi Yahya El Gharb", value: "sidiyahyaelgharb" },
  { label: "Sid L'Mokhtar", value: "sidlmokhtar" },
  { label: "Skhirat", value: "skhirat" },
  { label: "Smara", value: "smara" },
  { label: "Souk El Arbaa", value: "soukelarbaa" },
  { label: "Souk Sebt Oulad Nemma", value: "souksebtouladnemma" },
  { label: "Tabounte", value: "tabounte" },
  { label: "Tahla", value: "tahla" },
  { label: "Tamallalt", value: "tamallalt" },
  { label: "Tamesna", value: "tamesna" },
  { label: "Tamensourt", value: "tamensourt" },
  { label: "Tan-Tan", value: "tantan" },
  { label: "Tangier", value: "tangier" },
  { label: "Taounate", value: "taounate" },
  { label: "Taourirt", value: "taourirt" },
  { label: "Taroudant", value: "taroudant" },
  { label: "Tata", value: "tata" },
  { label: "Taza", value: "taza" },
  { label: "Temara", value: "temara" },
  { label: "Temsia", value: "temsia" },
  { label: "Tetouan", value: "tetouan" },
  { label: "Tichla", value: "tichla" },
  { label: "Tifariti", value: "tifariti" },
  { label: "Tiflet", value: "tiflet" },
  { label: "Tinghir", value: "tinghir" },
  { label: "Tit Mellil", value: "titmellil" },
  { label: "Tiznit", value: "tiznit" },
  { label: "Toulal", value: "toulal" },
  { label: "Youssoufia", value: "youssoufia" },
  { label: "Zaio", value: "zaio" },
  { label: "Zagora", value: "zagora" },
  { label: "Zaouiat Cheikh", value: "zaouiatcheikh" },
  { label: "Zeghanghane", value: "zeghanghane" },
  { label: "(Autre valeur)", value: "other" },
];

export const cityLabelMap = toLabelMap(cityOptions);