import Datasource from 'db/typeorm.config'
import { Team } from 'src/modules/team/entities/team.entity'
import { QualifCenter } from 'src/modules/team/entities/team.entity'

const teamCenters = [
  { id: 4, quadrigram: "TORE", center: "casablanca" },
  { id: 5, quadrigram: "MDYY", center: "casablanca" },
  { id: 8, quadrigram: "ALPH", center: "casablanca" },
  { id: 9, quadrigram: "BGMT", center: "online" },
  { id: 16, quadrigram: "IBAM", center: "casablanca" },
  { id: 17, quadrigram: "AHIS", center: "casablanca" },
  { id: 18, quadrigram: "CQFD", center: "rabat" },
  { id: 20, quadrigram: "ALGO", center: "casablanca" },
  { id: 22, quadrigram: "ATVS", center: "online" },
  { id: 26, quadrigram: "TWCP", center: "online" },
  { id: 27, quadrigram: "PIGE", center: "rabat" },
  { id: 28, quadrigram: "LPDN", center: "agadir" },
  { id: 29, quadrigram: "LGPN", center: "online" },
  { id: 30, quadrigram: "MAST", center: "rabat" },
  { id: 31, quadrigram: "MXTM", center: "rabat" },
  { id: 33, quadrigram: "MASC", center: "online" },
  { id: 35, quadrigram: "QUMI", center: "benguerir" },
  { id: 36, quadrigram: "ABEL", center: "online" },
  { id: 37, quadrigram: "TSRM", center: "casablanca" },
  { id: 38, quadrigram: "MMAA", center: "online" },
  { id: 39, quadrigram: "TMAT", center: "benguerir" },
  { id: 48, quadrigram: "MFAL", center: "rabat" },
  { id: 49, quadrigram: "PERS", center: "agadir" },
  { id: 53, quadrigram: "LFIB", center: "fez" },
  { id: 56, quadrigram: "PIMA", center: "benguerir" },
  { id: 57, quadrigram: "SLGM", center: "online" },
  { id: 60, quadrigram: "MTDR", center: "fez" },
  { id: 61, quadrigram: "MTSQ", center: "agadir" },
  { id: 62, quadrigram: "AXIO", center: "casablanca" },
  { id: 64, quadrigram: "MTHX", center: "online" },
  { id: 69, quadrigram: "XLGN", center: "benguerir" },
  { id: 70, quadrigram: "PPRT", center: "rabat" },
  { id: 79, quadrigram: "BYMA", center: "benguerir" },
  { id: 81, quadrigram: "LAPR", center: "benguerir" },
  { id: 84, quadrigram: "MACH", center: "online" },
  { id: 87, quadrigram: "BCOR", center: "rabat" },
  { id: 89, quadrigram: "ASRD", center: "online" },
  { id: 90, quadrigram: "BOOL", center: "online" },
  { id: 91, quadrigram: "MPWR", center: "fez" },
  { id: 93, quadrigram: "EUHZ", center: "benguerir" },
  { id: 97, quadrigram: "ALTX", center: "online" },
  { id: 98, quadrigram: "THUN", center: "rabat" },
  { id: 101, quadrigram: "MTHS", center: "rabat" },
  { id: 102, quadrigram: "MENJ", center: "rabat" },
  { id: 105, quadrigram: "ALWT", center: "martil" },
  { id: 106, quadrigram: "MAJD", center: "online" },
  { id: 108, quadrigram: "YGSZ", center: "online" },
  { id: 111, quadrigram: "ASTX", center: "casablanca" },
  { id: 113, quadrigram: "PEAK", center: "casablanca" },
  { id: 124, quadrigram: "ENZO", center: "benguerir" },
  { id: 126, quadrigram: "ALPT", center: "online" },
  { id: 138, quadrigram: "EPSO", center: "fez" },
  { id: 141, quadrigram: "TECH", center: "martil" },
  { id: 152, quadrigram: "NMRS", center: "online" },
  { id: 154, quadrigram: "VBNM", center: "online" },
  { id: 158, quadrigram: "AMAS", center: "rabat" },
  { id: 161, quadrigram: "IVAB", center: "rabat" },
  { id: 163, quadrigram: "SPRO", center: "online" },
  { id: 164, quadrigram: "NTRL", center: "fez" },
  { id: 168, quadrigram: "PIQU", center: "casablanca" },
  { id: 177, quadrigram: "GHTJ", center: "benguerir" },
  { id: 180, quadrigram: "CROI", center: "online" },
  { id: 189, quadrigram: "MRSC", center: "online" },
  { id: 195, quadrigram: "SMBG", center: "online" },
  { id: 209, quadrigram: "FYNL", center: "casablanca" },
  { id: 210, quadrigram: "MTEX", center: "casablanca" },
  { id: 211, quadrigram: "AMDM", center: "benguerir" },
  { id: 212, quadrigram: "NOMU", center: "rabat" },
  { id: 213, quadrigram: "MARC", center: "online" },
  { id: 214, quadrigram: "KSGT", center: "online" },
  { id: 218, quadrigram: "PRTS", center: "online" },
  { id: 223, quadrigram: "ISOM", center: "casablanca" },
  { id: 224, quadrigram: "PRMI", center: "rabat" },
  { id: 227, quadrigram: "SDHT", center: "benguerir" },
  { id: 229, quadrigram: "HRLM", center: "rabat" },
  { id: 235, quadrigram: "NMAT", center: "online" },
  { id: 236, quadrigram: "ARNS", center: "fez" },
  { id: 243, quadrigram: "GOBR", center: "online" },
  { id: 248, quadrigram: "LAR2", center: "online" },
  { id: 253, quadrigram: "SNFR", center: "online" },
  { id: 254, quadrigram: "PTLO", center: "martil" },
  { id: 260, quadrigram: "ZEDS", center: "fez" },
  { id: 261, quadrigram: "SKGP", center: "rabat" },
  { id: 263, quadrigram: "PSUS", center: "casablanca" },
  { id: 264, quadrigram: "ZERO", center: "online" },
  { id: 265, quadrigram: "BROS", center: "rabat" },
  { id: 267, quadrigram: "PIXI", center: "rabat" },
  { id: 276, quadrigram: "AVGR", center: "casablanca" },
  { id: 278, quadrigram: "SKYS", center: "agadir" },
  { id: 284, quadrigram: "SPMT", center: "rabat" },
  { id: 285, quadrigram: "MAT2", center: "martil" },
  { id: 286, quadrigram: "PRMS", center: "casablanca" },
  { id: 287, quadrigram: "MAMC", center: "casablanca" },
  { id: 290, quadrigram: "PWRS", center: "rabat" },
  { id: 291, quadrigram: "SHAO", center: "oujda" },
  { id: 293, quadrigram: "AZRY", center: "casablanca" },
  { id: 302, quadrigram: "KHAY", center: "benguerir" },
  { id: 312, quadrigram: "MEAO", center: "online" },
  { id: 321, quadrigram: "CPUP", center: "oujda" },
  { id: 328, quadrigram: "THPP", center: "online" },
  { id: 340, quadrigram: "UNUM", center: "online" },
  { id: 352, quadrigram: "LMDT", center: "casablanca" },
  { id: 356, quadrigram: "NVMX", center: "fez" },
  { id: 402, quadrigram: "SAPX", center: "martil" },
  { id: 410, quadrigram: "LMBR", center: "casablanca" },
  { id: 414, quadrigram: "BDGE", center: "benguerir" },
  { id: 417, quadrigram: "HBND", center: "benguerir" },
  { id: 420, quadrigram: "VCTX", center: "martil" },
  { id: 450, quadrigram: "IRMW", center: "online" },
  { id: 468, quadrigram: "TPFT", center: "casablanca" },
  { id: 474, quadrigram: "TGGI", center: "fez" },
  { id: 483, quadrigram: "LOGL", center: "online" },
  { id: 494, quadrigram: "RADK", center: "casablanca" },
  { id: 505, quadrigram: "MLGC", center: "casablanca" },
  { id: 517, quadrigram: "MBMS", center: "casablanca" },
  { id: 520, quadrigram: "FERR", center: "fez" },
  { id: 521, quadrigram: "CDOR", center: "online" },
  { id: 523, quadrigram: "MTTN", center: "online" },
  { id: 537, quadrigram: "CLYX", center: "online" },
  { id: 539, quadrigram: "CART", center: "rabat" },
  { id: 553, quadrigram: "MTMG", center: "martil" },
  { id: 565, quadrigram: "AKMD", center: "online" },
  { id: 573, quadrigram: "TMXF", center: "rabat" },
  { id: 579, quadrigram: "ASTR", center: "casablanca" },
  { id: 581, quadrigram: "LSDP", center: "casablanca" },
  { id: 606, quadrigram: "OTOG", center: "oujda" },
  { id: 608, quadrigram: "NRJS", center: "rabat" },
  { id: 613, quadrigram: "SOLV", center: "online" },
  { id: 614, quadrigram: "QEDX", center: "casablanca" },
  { id: 621, quadrigram: "MPDG", center: "rabat" },
  { id: 623, quadrigram: "PYTH", center: "martil" },
  { id: 626, quadrigram: "MMVI", center: "online" },
  { id: 635, quadrigram: "TNMD", center: "agadir" },
  { id: 650, quadrigram: "DTMY", center: "online" },
  { id: 651, quadrigram: "MLGM", center: "benguerir" },
  { id: 653, quadrigram: "ENMA", center: "casablanca" },
  { id: 682, quadrigram: "SOPI", center: "agadir" },
  { id: 683, quadrigram: "VTAL", center: "online" },
  { id: 692, quadrigram: "LAQP", center: "online" },
  { id: 701, quadrigram: "DVNT", center: "rabat" },
  { id: 706, quadrigram: "TTSH", center: "casablanca" },
  { id: 713, quadrigram: "LMBJ", center: "martil" },
  { id: 714, quadrigram: "MTWE", center: "online" },
  { id: 715, quadrigram: "MTPW", center: "agadir" },
  { id: 716, quadrigram: "OURT", center: "fez" },
  { id: 718, quadrigram: "MATJ", center: "benguerir" },
]

async function assignToQualifCenters() {
  const teamRepo = Datasource.getRepository(Team)
  
  const idsByCenter = teamCenters.reduce<Record<string, number[]>>((acc, t) => {
    (acc[t.center] ??= []).push(t.id)
    return acc
  }, {})

  for (const [center, ids] of Object.entries(idsByCenter)) {
    const result = await teamRepo
      .createQueryBuilder()
      .update(Team)
      .set({ qualifCenter: center as QualifCenter })
      .whereInIds(ids)
      .execute()

    console.log(`Assigned ${result.affected}/${ids.length} teams to "${center}"`)
  }   
}

Datasource.initialize()
  .then(async () => {
    await assignToQualifCenters()
    await Datasource.destroy()
  })
  .catch((err) => console.error(err))