export const organizingCommittee = [
  { name: "Bilal Bahchani", linkedinSrc: "https://www.linkedin.com/in/bilal-bahchani-933325326/" },
  { name: "Omar Bennouna", linkedinSrc: "https://www.linkedin.com/in/omar-bennouna-a6b64b197/", imageSrc: "omar_bennouna.webp" },
  { name: "Ilyass Bouazza", linkedinSrc: "https://www.linkedin.com/in/ilyass-bouazza-98030b290/", imageSrc: "ilyass_bouazza.webp" },
  { name: "Hiba El Kasimi", linkedinSrc: "https://www.linkedin.com/in/hiba-el-kasimi/" },
  { name: "Hamza Lasri", linkedinSrc: "https://www.linkedin.com/in/hamza-lasri-bb8347247/", imageSrc: "hamza_lasri.webp" },
  { name: "Chaimaa Loutfi", linkedinSrc: "https://www.linkedin.com/in/chaimaa-loutfi-93bba821a/", imageSrc: "chaimaa_loutfi.webp" },
  { name: "Kawtar Taik", linkedinSrc: "https://www.linkedin.com/in/kawtar-ta%C3%AFk-7544a11b9/" },
  { name: "Malak Khaldouni" },
  { name: "Mohammed-Taha En-nahili", linkedinSrc: "https://www.linkedin.com/in/mohammed-taha-en-nahili-655322303/", imageSrc: "Mohammed_Taha_En-nahili.webp" },
  { name: "Lina Bellahmidi", linkedinSrc: "https://www.linkedin.com/in/lina-bellahmidi-0b1251248/" },
  { name: "Ali Noufli" },
  { name: "Amine Hbar", linkedinSrc: "https://www.linkedin.com/in/amine-hbar-0748a2246/" },
  { name: "Jad Lasiri", linkedinSrc: "https://www.linkedin.com/in/jad-lasiri-6b7bb0292/" },
  { name: "Ayman Amasrour", linkedinSrc: "https://www.linkedin.com/in/ayman-amasrour-1a280228a/", imageSrc: "ayman_amasrour.webp" },
  { name: "Mohamed Reda El Messaoudi", linkedinSrc: "https://www.linkedin.com/in/mohamed-reda-el-messaoudi-bb21b2332/" },
  { name: "FatimaZahra Moudakir", linkedinSrc: "https://www.linkedin.com/in/fatima-zahra-moudakir-615527246/" },
  { name: "Achraf El Khamsi", linkedinSrc: "https://www.linkedin.com/in/achrafelkhamsi/", imageSrc: "achraf_el_khamsi.webp" },
  { name: "Omar Fathallah", linkedinSrc: "https://www.linkedin.com/in/omar-fathallah-/" },
  { name: "Souhail El Bakkar", linkedinSrc: "https://www.linkedin.com/in/souhail-elbakkar-9aab2a284/", imageSrc: "souhail_elbakkare.webp" },
  { name: "Wassel Ben Yahia", linkedinSrc: "https://www.linkedin.com/in/wassel-ben-yahia-2b14aa244/", imageSrc: "wassel_benyahya.webp" },
  { name: "Abdelkayoum Kaddouri", linkedinSrc: "https://www.linkedin.com/in/abdelkayoum-kaddouri-1213ab321/", imageSrc: "abdelkayoum_kaddouri.webp" },
  { name: "Rinas Nejjari", linkedinSrc: "https://www.linkedin.com/in/rinas-nejjari-1ba702358/", imageSrc: "rinas_nejjari.webp" },
  { name: "Ismail Bouhaj", linkedinSrc: "https://www.linkedin.com/in/ismail-bouhaj-240745235/" },
  { name: "Nour El Houda El Bouz", linkedinSrc: "https://www.linkedin.com/in/el-bouz-nour-el-houda-631425308/", imageSrc: "nour_el_houda_el_bouz.webp" },
  { name: "Rania Daya", linkedinSrc: "https://www.linkedin.com/in/rania-daya-09b758296/" },
  { name: "Mouad Enoua", linkedinSrc: "https://www.linkedin.com/in/mouad-enoua-48a984327/", imageSrc: "mouad_enoua.webp" },
  { name: "Manal Saoui", linkedinSrc: "https://www.linkedin.com/in/manal-saoui/", imageSrc: "manal_saoui.webp" },
  { name: "Ayoub Bennouna", linkedinSrc: "https://www.linkedin.com/in/ayoub-bennouna-00273823a/", imageSrc: "ayoub_bennouna.webp" }
];

export const webDevelopment = []