version: '3.1'

services:
  mtym_db:
    image: mysql
    container_name: mtym_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  mtym_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mtym_phpmyadmin
    links:
      - mtym_db
    environment:
      - PMA_HOST=mtym_db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80