services:
  minio:
    image: minio/minio
    container_name: mtym_s3
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - s3_data:/data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./minio/anonymous-policy.json:/policy/anonymous-policy.json:ro
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do sleep 2; done;
      mc mb --ignore-existing local/$${MINIO_BUCKET_NAME};
      sed s/__BUCKET__/$${MINIO_BUCKET_NAME}/g /policy/anonymous-policy.json > /tmp/anonymous-policy.json;
      mc anonymous set-json /tmp/anonymous-policy.json local/$${MINIO_BUCKET_NAME};
      exit 0;
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}

volumes:
  s3_data:

